name: Build and Test Action

on:
  push:
    branches: 
      - "development"     # Trigger on push to development branch
      - "main"            # Trigger on push to main branch
      - "feature/*"       # Trigger on push to any feature branch
  pull_request:
    branches: 
      - "development"     # Trigger on PRs to development branch
      - "main"            # Trigger on PRs to main branch
  schedule:
    - cron: "0 3 * * 1"   # Trigger every Monday at 3:00 AM UTC
  workflow_dispatch:        # Allows manual trigger via GitHub UI

env:
  JAVA_DISTRIBUTION: "corretto"
  JAVA_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.m2/wrapper
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/.mvn/wrapper/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-wrapper-

      - name: Set up JDK 21 Amazon Corretto
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B package --file OutbackWeatherTrackerApplication/pom.xml install -DskipTests

  test:
    needs: build  
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 for testing
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Run Maven Tests for DBTests
        run: mvn -B test --file OutbackWeatherTrackerApplication/pom.xml -Dtest="DBTests.**.*Test"
