name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - development
      - feature/*
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 Amazon Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Javadoc
        run: mvn javadoc:javadoc --file pom.xml

      - name: Commit Javadocs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -f target/site/apidocs
          git commit -m "Deploy Javadoc to GitHub"
          git push -f
          
          
          
          
          