name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - development
      - feature/*
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 Amazon Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish JavaDocs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: OutbackWeatherTrackerApplication/target/javadocs
          